{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tsm.fullname" . }}-backend
  labels:
    {{- include "tsm.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "tsm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
