apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: tsm-backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: tsm-frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: ConfigMap
      name: tsm-config
    patch: |
      - op: replace
        path: /data/TSM_DEV_MODE
        value: "true"
      - op: replace
        path: /data/TSM_LOG_LEVEL
        value: "debug"
