apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "tsm.labels" . | nindent 4 }}
type: Opaque
stringData:
  TSM_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  TSM_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  TSM_OIDC_ISSUER: {{ .Values.secrets.oidcIssuer | quote }}
  TSM_OIDC_CLIENT_ID: {{ .Values.secrets.oidcClientId | quote }}
  TSM_OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  TSM_OIDC_REDIRECT_URL: {{ .Values.secrets.oidcRedirectUrl | quote }}
