// Package docs embeds the generated Swagger 2.0 JSON specification into
// the server binary at compile time. The spec is generated by swag from
// handler annotations — run `make swag` to regenerate after handler changes.
package docs

import _ "embed"

// SwaggerJSON holds the raw bytes of the generated swagger.json spec.
//
//go:embed swagger.json
var SwaggerJSON []byte
