// Package docs embeds the generated Swagger 2.0 JSON specification into the
// server binary at compile time. The spec is generated by swag from handler
// annotations — run `make swag` (or `swag init -g cmd/server/main.go
// --outputTypes json`) to regenerate after handler changes.
package docs

import (
	_ "embed"

	"gopkg.in/yaml.v3"
)

// SwaggerJSON holds the raw bytes of the generated swagger.json spec.
//
//go:embed swagger.json
var SwaggerJSON []byte

// SwaggerYAML is the spec re-encoded as YAML, served at /swagger.yaml. Derived
// from SwaggerJSON at init; falls back to the JSON bytes (valid YAML) on error.
var SwaggerYAML = jsonToYAML(SwaggerJSON)

func jsonToYAML(jsonBytes []byte) []byte {
	var doc interface{}
	if err := yaml.Unmarshal(jsonBytes, &doc); err != nil {
		return jsonBytes
	}
	out, err := yaml.Marshal(doc)
	if err != nil {
		return jsonBytes
	}
	return out
}
