apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tsm-ingress
  labels:
    app: tsm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: tsm.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tsm-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tsm-frontend
                port:
                  number: 80
